#include "one/set.h"

enum { ONE_SET_RANGE = 1, ONE_SET_SYMBOLS = 2 };

static one_set_status_t one_set_bytes(size_t cap, size_t *out) { if (out == 0) return ONESET_ERR_INVALID_ARGUMENT; if (cap > SIZE_MAX - 7u) return ONESET_ERR_OVERFLOW; *out = (cap + 7u) / 8u; return ONESET_OK; }
static one_set_status_t one_set_schema(const one_set_position_t *p, size_t n, size_t *cap) { size_t i, a, b, c = 1u; if (p == 0 || cap == 0 || n == 0u) return ONESET_ERR_INVALID_ARGUMENT; for (i = 0u; i < n; ++i) { if (p[i].symbols == 0 || p[i].count == 0u) return ONESET_ERR_INVALID_SCHEMA; for (a = 0u; a < p[i].count; ++a) for (b = a + 1u; b < p[i].count; ++b) if (p[i].symbols[a] == p[i].symbols[b]) return ONESET_ERR_DUPLICATE_SYMBOL; if (c > SIZE_MAX / p[i].count) return ONESET_ERR_OVERFLOW; c *= p[i].count; } *cap = c; return ONESET_OK; }
static int one_set_valid(const one_set_t *s) { size_t b; return s != 0 && (s->mode == ONE_SET_RANGE || s->mode == ONE_SET_SYMBOLS) && s->storage != 0 && one_set_bytes(s->capacity, &b) == ONESET_OK && s->storage_size >= b; }

one_set_status_t one_set_required_bytes_range(uint32_t min, uint32_t max, size_t *out) { uint64_t cap; if (min > max) return ONESET_ERR_INVALID_RANGE; cap = (uint64_t)max - min + 1u; if (cap > SIZE_MAX) return ONESET_ERR_OVERFLOW; return one_set_bytes((size_t)cap, out); }
one_set_status_t one_set_required_bytes_symbols(const one_set_position_t *p, size_t n, size_t *out) { size_t c; one_set_status_t st = one_set_schema(p, n, &c); return st == ONESET_OK ? one_set_bytes(c, out) : st; }
one_set_status_t one_set_init_range(one_set_t *s, uint32_t min, uint32_t max, void *storage, size_t size) { size_t bytes; one_set_status_t st; if (s == 0 || storage == 0) return ONESET_ERR_INVALID_ARGUMENT; st = one_set_required_bytes_range(min, max, &bytes); if (st != ONESET_OK) return st; if (size < bytes) return ONESET_ERR_STORAGE_TOO_SMALL; s->mode=ONE_SET_RANGE;s->min_value=min;s->capacity=(size_t)((uint64_t)max-min+1u);s->storage=storage;s->storage_size=size;s->positions=0;s->position_count=0u;return ONESET_OK; }
one_set_status_t one_set_init_symbols(one_set_t *s, const one_set_position_t *p, size_t n, void *storage, size_t size) { size_t c,b; one_set_status_t st; if(s==0||storage==0)return ONESET_ERR_INVALID_ARGUMENT; st=one_set_schema(p,n,&c);if(st!=ONESET_OK)return st;st=one_set_bytes(c,&b);if(st!=ONESET_OK)return st;if(size<b)return ONESET_ERR_STORAGE_TOO_SMALL;s->mode=ONE_SET_SYMBOLS;s->min_value=0u;s->capacity=c;s->storage=storage;s->storage_size=size;s->positions=p;s->position_count=n;return ONESET_OK; }
one_set_status_t one_set_index_u32(const one_set_t *s,uint32_t v,size_t *out){if(!one_set_valid(s)||out==0)return ONESET_ERR_INVALID_ARGUMENT;if(s->mode!=ONE_SET_RANGE)return ONESET_ERR_WRONG_MODE;if(v<s->min_value||(uint64_t)v-s->min_value>=s->capacity)return ONESET_ERR_INVALID_KEY;*out=(size_t)((uint64_t)v-s->min_value);return ONESET_OK;}
one_set_status_t one_set_index(const one_set_t *s,const uint8_t *k,size_t *out){size_t i,index=0u;if(!one_set_valid(s)||k==0||out==0)return ONESET_ERR_INVALID_ARGUMENT;if(s->mode!=ONE_SET_SYMBOLS)return ONESET_ERR_WRONG_MODE;for(i=0u;i<s->position_count;++i){size_t o;for(o=0u;o<s->positions[i].count&&s->positions[i].symbols[o]!=k[i];++o){}if(o==s->positions[i].count)return ONESET_ERR_INVALID_KEY;index=index*s->positions[i].count+o;}*out=index;return ONESET_OK;}
bool one_set_contains_index(const one_set_t *s,size_t i){return one_set_valid(s)&&i<s->capacity&&(s->storage[i>>3]&(uint8_t)(1u<<(i&7u)))!=0u;}
void one_set_add_index(one_set_t *s,size_t i){if(one_set_valid(s)&&i<s->capacity)s->storage[i>>3]|=(uint8_t)(1u<<(i&7u));}
void one_set_remove_index(one_set_t *s,size_t i){if(one_set_valid(s)&&i<s->capacity)s->storage[i>>3]&=(uint8_t)~(uint8_t)(1u<<(i&7u));}
one_set_status_t one_set_contains_u32_checked(const one_set_t*s,uint32_t v,bool*out){size_t i;one_set_status_t st;if(out==0)return ONESET_ERR_INVALID_ARGUMENT;st=one_set_index_u32(s,v,&i);if(st==ONESET_OK)*out=one_set_contains_index(s,i);return st;}
one_set_status_t one_set_contains_checked(const one_set_t*s,const uint8_t*k,bool*out){size_t i;one_set_status_t st;if(out==0)return ONESET_ERR_INVALID_ARGUMENT;st=one_set_index(s,k,&i);if(st==ONESET_OK)*out=one_set_contains_index(s,i);return st;}
bool one_set_contains_u32(const one_set_t*s,uint32_t v){bool b=false;return one_set_contains_u32_checked(s,v,&b)==ONESET_OK&&b;}
bool one_set_contains(const one_set_t*s,const uint8_t*k){bool b=false;return one_set_contains_checked(s,k,&b)==ONESET_OK&&b;}
one_set_status_t one_set_add_u32(one_set_t*s,uint32_t v){size_t i;one_set_status_t st=one_set_index_u32(s,v,&i);if(st==ONESET_OK)one_set_add_index(s,i);return st;}
one_set_status_t one_set_remove_u32(one_set_t*s,uint32_t v){size_t i;one_set_status_t st=one_set_index_u32(s,v,&i);if(st==ONESET_OK)one_set_remove_index(s,i);return st;}
one_set_status_t one_set_add(one_set_t*s,const uint8_t*k){size_t i;one_set_status_t st=one_set_index(s,k,&i);if(st==ONESET_OK)one_set_add_index(s,i);return st;}
one_set_status_t one_set_remove(one_set_t*s,const uint8_t*k){size_t i;one_set_status_t st=one_set_index(s,k,&i);if(st==ONESET_OK)one_set_remove_index(s,i);return st;}
void one_set_clear(one_set_t*s){size_t i,b;if(!one_set_valid(s)||one_set_bytes(s->capacity,&b)!=ONESET_OK)return;for(i=0u;i<b;++i)s->storage[i]=0u;}
void one_set_fill(one_set_t*s){size_t i,b;if(!one_set_valid(s)||one_set_bytes(s->capacity,&b)!=ONESET_OK)return;for(i=0u;i<b;++i)s->storage[i]=UINT8_MAX;if((s->capacity&7u)!=0u)s->storage[b-1u]=(uint8_t)((1u<<(s->capacity&7u))-1u);}
