#include "one/stat.h"

enum { ONE_STAT_RANGE = 1, ONE_STAT_SYMBOLS = 2 };
static int width_ok(uint8_t b){return b==1u||b==2u||b==4u||b==8u||b==16u||b==32u;}
static one_stat_status_t layout(const uint8_t*b,size_t n,size_t cap,size_t*out_bits,size_t*out_bytes){size_t i,r=0,total;if(b==0||n==0u||out_bits==0||out_bytes==0)return ONESTAT_ERR_INVALID_ARGUMENT;for(i=0;i<n;++i){if(!width_ok(b[i]))return ONESTAT_ERR_INVALID_WIDTH;if(r>SIZE_MAX-b[i])return ONESTAT_ERR_OVERFLOW;r+=b[i];}if(cap> (SIZE_MAX-7u)/r)return ONESTAT_ERR_OVERFLOW;total=cap*r;*out_bits=r;*out_bytes=(total+7u)/8u;return ONESTAT_OK;}
static int valid(const one_stat_t*s){size_t b,r;return s!=0&&(s->mode==ONE_STAT_RANGE||s->mode==ONE_STAT_SYMBOLS)&&s->storage!=0&&layout(s->field_bits,s->field_count,s->capacity,&r,&b)==ONESTAT_OK&&s->storage_size>=b;}
static one_stat_status_t symbols(const one_stat_position_t*p,size_t n,size_t*out){size_t i,a,b,c=1u;if(p==0||out==0||n==0u)return ONESTAT_ERR_INVALID_ARGUMENT;for(i=0u;i<n;++i){if(p[i].symbols==0||p[i].count==0u)return ONESTAT_ERR_INVALID_SCHEMA;for(a=0u;a<p[i].count;++a)for(b=a+1u;b<p[i].count;++b)if(p[i].symbols[a]==p[i].symbols[b])return ONESTAT_ERR_DUPLICATE_SYMBOL;if(c>SIZE_MAX/p[i].count)return ONESTAT_ERR_OVERFLOW;c*=p[i].count;}*out=c;return ONESTAT_OK;}
one_stat_status_t one_stat_required_bytes_range(uint32_t min,uint32_t max,const uint8_t*b,size_t n,size_t*out){uint64_t c;if(min>max)return ONESTAT_ERR_INVALID_RANGE;c=(uint64_t)max-min+1u;if(c>SIZE_MAX)return ONESTAT_ERR_OVERFLOW;{size_t r;return layout(b,n,(size_t)c,&r,out);}}
one_stat_status_t one_stat_required_bytes_symbols(const one_stat_position_t*p,size_t pn,const uint8_t*b,size_t n,size_t*out){size_t c,r;one_stat_status_t st=symbols(p,pn,&c);return st==ONESTAT_OK?layout(b,n,c,&r,out):st;}
one_stat_status_t one_stat_init_range(one_stat_t*s,uint32_t min,uint32_t max,const uint8_t*b,size_t n,void*storage,size_t size){size_t need,r;one_stat_status_t st;if(s==0||storage==0)return ONESTAT_ERR_INVALID_ARGUMENT;st=one_stat_required_bytes_range(min,max,b,n,&need);if(st!=ONESTAT_OK)return st;if(size<need)return ONESTAT_ERR_STORAGE_TOO_SMALL;layout(b,n,(size_t)((uint64_t)max-min+1u),&r,&need);s->mode=ONE_STAT_RANGE;s->min_value=min;s->capacity=(size_t)((uint64_t)max-min+1u);s->field_bits=b;s->field_count=n;s->record_bits=r;s->storage=storage;s->storage_size=size;s->positions=0;s->position_count=0;return ONESTAT_OK;}
one_stat_status_t one_stat_init_symbols(one_stat_t*s,const one_stat_position_t*p,size_t pn,const uint8_t*b,size_t n,void*storage,size_t size){size_t c,need,r;one_stat_status_t st;if(s==0||storage==0)return ONESTAT_ERR_INVALID_ARGUMENT;st=symbols(p,pn,&c);if(st!=ONESTAT_OK)return st;st=layout(b,n,c,&r,&need);if(st!=ONESTAT_OK)return st;if(size<need)return ONESTAT_ERR_STORAGE_TOO_SMALL;s->mode=ONE_STAT_SYMBOLS;s->min_value=0u;s->capacity=c;s->field_bits=b;s->field_count=n;s->record_bits=r;s->storage=storage;s->storage_size=size;s->positions=p;s->position_count=pn;return ONESTAT_OK;}
static one_stat_status_t offset(const one_stat_t*s,size_t i,size_t f,size_t*o){size_t j,base;if(!valid(s))return ONESTAT_ERR_INVALID_ARGUMENT;if(i>=s->capacity)return ONESTAT_ERR_INDEX_OUT_OF_RANGE;if(f>=s->field_count)return ONESTAT_ERR_FIELD_OUT_OF_RANGE;base=i*s->record_bits;for(j=0;j<f;++j)base+=s->field_bits[j];*o=base;return ONESTAT_OK;}
static uint32_t readbits(const one_stat_t*s,size_t o,uint8_t w){uint32_t v=0;uint8_t k;for(k=0;k<w;++k)if((s->storage[(o+k)>>3]&(uint8_t)(1u<<((o+k)&7u)))!=0u)v|=UINT32_C(1)<<k;return v;}
static void writebits(one_stat_t*s,size_t o,uint8_t w,uint32_t v){uint8_t k;for(k=0;k<w;++k){uint8_t m=(uint8_t)(1u<<((o+k)&7u));uint8_t* p=&s->storage[(o+k)>>3];if((v&(UINT32_C(1)<<k))!=0u)*p|=m;else *p&=(uint8_t)~m;}}
one_stat_status_t one_stat_get_index(const one_stat_t*s,size_t i,size_t f,uint32_t*out){size_t o;one_stat_status_t st;if(out==0)return ONESTAT_ERR_INVALID_ARGUMENT;st=offset(s,i,f,&o);if(st==ONESTAT_OK)*out=readbits(s,o,s->field_bits[f]);return st;}
one_stat_status_t one_stat_set_index(one_stat_t*s,size_t i,size_t f,uint32_t v){size_t o;one_stat_status_t st=offset(s,i,f,&o);if(st!=ONESTAT_OK)return st;if(s->field_bits[f]<32u&&v>=(UINT32_C(1)<<s->field_bits[f]))return ONESTAT_ERR_VALUE_OUT_OF_RANGE;writebits(s,o,s->field_bits[f],v);return ONESTAT_OK;}
one_stat_status_t one_stat_add_index(one_stat_t*s,size_t i,size_t f,uint32_t d){uint32_t v,max;one_stat_status_t st=one_stat_get_index(s,i,f,&v);if(st!=ONESTAT_OK)return st;max=s->field_bits[f]==32u?UINT32_MAX:(UINT32_C(1)<<s->field_bits[f])-1u;return one_stat_set_index(s,i,f,d>max-v?max:v+d);}
one_stat_status_t one_stat_inc_index(one_stat_t*s,size_t i,size_t f){return one_stat_add_index(s,i,f,1u);} one_stat_status_t one_stat_dec_index(one_stat_t*s,size_t i,size_t f){uint32_t v;one_stat_status_t st=one_stat_get_index(s,i,f,&v);return st==ONESTAT_OK?one_stat_set_index(s,i,f,v==0u?0u:v-1u):st;} one_stat_status_t one_stat_reset_index(one_stat_t*s,size_t i,size_t f){return one_stat_set_index(s,i,f,0u);}
static one_stat_status_t ix(const one_stat_t*s,uint32_t id,size_t*out){if(!valid(s)||out==0)return ONESTAT_ERR_INVALID_ARGUMENT;if(s->mode!=ONE_STAT_RANGE)return ONESTAT_ERR_WRONG_MODE;if(id<s->min_value||(uint64_t)id-s->min_value>=s->capacity)return ONESTAT_ERR_INVALID_KEY;*out=(size_t)((uint64_t)id-s->min_value);return ONESTAT_OK;}
one_stat_status_t one_stat_get_u32(const one_stat_t*s,uint32_t id,size_t f,uint32_t*out){size_t i;one_stat_status_t st=ix(s,id,&i);return st==ONESTAT_OK?one_stat_get_index(s,i,f,out):st;} one_stat_status_t one_stat_set_u32(one_stat_t*s,uint32_t id,size_t f,uint32_t v){size_t i;one_stat_status_t st=ix(s,id,&i);return st==ONESTAT_OK?one_stat_set_index(s,i,f,v):st;} one_stat_status_t one_stat_inc_u32(one_stat_t*s,uint32_t id,size_t f){size_t i;one_stat_status_t st=ix(s,id,&i);return st==ONESTAT_OK?one_stat_inc_index(s,i,f):st;} one_stat_status_t one_stat_dec_u32(one_stat_t*s,uint32_t id,size_t f){size_t i;one_stat_status_t st=ix(s,id,&i);return st==ONESTAT_OK?one_stat_dec_index(s,i,f):st;} one_stat_status_t one_stat_add_u32(one_stat_t*s,uint32_t id,size_t f,uint32_t d){size_t i;one_stat_status_t st=ix(s,id,&i);return st==ONESTAT_OK?one_stat_add_index(s,i,f,d):st;} one_stat_status_t one_stat_reset_u32(one_stat_t*s,uint32_t id,size_t f){size_t i;one_stat_status_t st=ix(s,id,&i);return st==ONESTAT_OK?one_stat_reset_index(s,i,f):st;}
static one_stat_status_t keyix(const one_stat_t*s,const uint8_t*k,size_t*out){size_t i,index=0u;if(!valid(s)||k==0||out==0)return ONESTAT_ERR_INVALID_ARGUMENT;if(s->mode!=ONE_STAT_SYMBOLS)return ONESTAT_ERR_WRONG_MODE;for(i=0u;i<s->position_count;++i){size_t o;for(o=0u;o<s->positions[i].count&&s->positions[i].symbols[o]!=k[i];++o){}if(o==s->positions[i].count)return ONESTAT_ERR_INVALID_KEY;index=index*s->positions[i].count+o;}*out=index;return ONESTAT_OK;}
one_stat_status_t one_stat_get(const one_stat_t*s,const uint8_t*k,size_t f,uint32_t*out){size_t i;one_stat_status_t st=keyix(s,k,&i);return st==ONESTAT_OK?one_stat_get_index(s,i,f,out):st;} one_stat_status_t one_stat_set(one_stat_t*s,const uint8_t*k,size_t f,uint32_t v){size_t i;one_stat_status_t st=keyix(s,k,&i);return st==ONESTAT_OK?one_stat_set_index(s,i,f,v):st;} one_stat_status_t one_stat_inc(one_stat_t*s,const uint8_t*k,size_t f){size_t i;one_stat_status_t st=keyix(s,k,&i);return st==ONESTAT_OK?one_stat_inc_index(s,i,f):st;} one_stat_status_t one_stat_dec(one_stat_t*s,const uint8_t*k,size_t f){size_t i;one_stat_status_t st=keyix(s,k,&i);return st==ONESTAT_OK?one_stat_dec_index(s,i,f):st;} one_stat_status_t one_stat_add(one_stat_t*s,const uint8_t*k,size_t f,uint32_t d){size_t i;one_stat_status_t st=keyix(s,k,&i);return st==ONESTAT_OK?one_stat_add_index(s,i,f,d):st;} one_stat_status_t one_stat_reset(one_stat_t*s,const uint8_t*k,size_t f){size_t i;one_stat_status_t st=keyix(s,k,&i);return st==ONESTAT_OK?one_stat_reset_index(s,i,f):st;}
void one_stat_clear(one_stat_t*s){size_t i,b,r;if(!valid(s)||layout(s->field_bits,s->field_count,s->capacity,&r,&b)!=ONESTAT_OK)return;for(i=0;i<b;++i)s->storage[i]=0u;}
